services:
  - type: web
    name: cinepulse
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma db push --schema=server/prisma/schema.prisma && npm run prisma:seed -w server && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://cinepulse-gw3d.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: cinepulse-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: MOCK_PAYMENT_ENABLED
        value: "true"
      - key: CONVENIENCE_FEE_PERCENT
        value: "8"
      - key: DEFAULT_CITY
        value: Bhubaneswar

databases:
  - name: cinepulse-db
    plan: free
    databaseName: cinepulse
    user: cinepulse
